// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table property {
  unit_id integer [primary key, ref: > unit.unit_id]
  property_id integer [pk]
  name varchar [not null]
  url varchar
  created_at timestamp [not null]
  updated_at timestamp

  indexes {
    name [unique, name: "idx_property_name"]
  }

  note: '''
    Defines a unit of measure,
    which is a multi-line string
  '''
}
